services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: bash -lc "cp -f .env.docker .env && php -r 'while(true){$c=@pg_connect(\"host=\".getenv(\"DB_HOST\").\" port=\".getenv(\"DB_PORT\").\" dbname=\".getenv(\"DB_DATABASE\").\" user=\".getenv(\"DB_USERNAME\").\" password=\".getenv(\"DB_PASSWORD\"));if($c){pg_close($c);break;}sleep(1);}'; php artisan migrate --force || true; php-fpm"

  web:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: secret123
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:


